highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://nanzhouzzz.github.io/viate/
author: Nan Zhou

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /viate/
title: NanZhou's Resume
name: Nan Zhou
email: zhounan@sjtu.edu.cn
email_full: mailto:zhounan@sjtu.edu.cn
website: github.io/NanZhouzzz
website_full: https://NanZhouzzz.github.io/viate
github: NanZhouzzz
twitter: BlayneZhou
tel: +86  34204164
tel_full: tel:+8634204164
google_maps: 'https://www.google.co.uk/maps/place/Smart+Grid+Center,+Shanghhai,+China'
address:
  street: Room 301 Smart Grid Center
  postcode: 200240
  city: Shanghai Jiaotong Univeristy, Shanghai
  country: China
google_analytics: 

# needed for travis-ci build
exclude: [vendor]
